### ISSUE TITLE
Poetry GH action

### ISSUE THREAD

**Issue by matt035343** [SneaksAndData/github-actions#2]
Make a GH action that unifies the way to setup Poetry in the pipelines. More specifically, below code is boilerplate for all pipelines and can be replaced by a custom action. The last line with export of requirements is an optional step.

Further more, find out if this belongs in a different repo or this repo can be used for all GH actions we will make. In the latter case I recommend renaming the repo.

```yaml
      - name: Install Poetry
        env:
          REPO_URL: ${{ secrets.AZOPS_PYPI_REPO_URL }}
        run: |
          set -e

          curl -sSL https://install.python-poetry.org | python3 - --preview
          poetry config repositories.azops $REPO_URL
      - name: Install Dependencies
        env:
          POETRY_HTTP_BASIC_AZOPS_USERNAME: ${{ secrets.AZOPS_PAT_USER }}
          POETRY_HTTP_BASIC_AZOPS_PASSWORD: ${{ secrets.AZOPS_PAT }}
        run: |
          set -e

          poetry install

          poetry export -f requirements.txt --output .container/requirements.txt --without-hashes --with-credentials
```
