### ISSUE TITLE
Poetry action doesn't work with package publishing

### ISSUE THREAD

**Issue by george-zubrienko** [SneaksAndData/github-actions#22]
When using this action config:

```
      - name: Install Poetry
        uses: SneaksAndData/github-actions/install_poetry@v0.0.8
        with:
          pypi_repo_url: ${{ secrets.AZOPS_PYPI_UPLOAD }}
          pypi_token_username: ${{ secrets.AZOPS_PAT_USER }}
          pypi_token: ${{ secrets.AZOPS_PAT }}
          skip_dependencies: true
```

Which I assume should set repo url to the one used for uploads, I get 405 method not allowed - which means repo url stayed the same.
