### ISSUE TITLE
Add action for configuring AWS CA credentials

### ISSUE THREAD

**Issue by george-zubrienko** [SneaksAndData/github-actions#63]
## Action interface

```
      - name: Setup AWS CA
        uses: SneaksAndData/github-actions/setup_aws_ca@v0.1.0
        with:
          aws-access-key: ...
          aws-access-key-id: ...
          aws-region: eu-central-1 (default)
          mode: read,publish
          aws_ca_domain: some-domain
          aws_ca_domain_owner: some-domain-owner
        id: aws_ca
```

Action content smth like this:

```

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ env.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Fetch AWS CA token
        run: |
          set -e
          
          awsca_token="$(aws codeartifact get-authorization-token --domain $aws_ca_domain --domain-owner $aws_ca_domain_owner --region eu-central-1 --query authorizationToken --output text)"
          if [[ "$mode" == "read" ]]
          then
           awsca_url="$(aws codeartifact get-repository-endpoint --domain $aws_ca_domain --domain-owner $aws_ca_domain_owner --repository esd-artifacts --region eu-central-1 --format pypi --query repositoryEndpoint --output text)/simple/"
          fi
          if [[ "$mode" == "publish" ]]
          then
                       awsca_url="$(aws codeartifact get-repository-endpoint --domain $aws_ca_domain --domain-owner $aws_ca_domain_owner --repository esd-artifacts --region eu-central-1 --format pypi --query repositoryEndpoint --output text)"
            fi
         
          
          echo "::add-mask::$awsca_token" 
          echo "AWSCA_TOKEN=$awsca_token" >> ${GITHUB_ENV}
          
          echo "::add-mask::$awsca_url" 
          echo "AWSCA_URL=$awsca_url" >> ${GITHUB_ENV}

         <same for awsca_user=aws>
```

Action output to be used like this:
```
      - name: Install Poetry and dependencies
        uses: SneaksAndData/github-actions/install_poetry@v0.1.0
        with:
          pypi_repo_url: ${{ aws_ca.output.AWSCA_URL }}
          pypi_token_username: ${{ aws_ca.output.AWSCA_USER }}
          pypi_token: ${{ aws_ca.output.AWSCA_TOKEN }}
```
